### PR TITLE
feature: support write span via grpc stream

### LINKED ISSUE #109: Support writeSpan via grpc stream
## Requirement - what kind of business use case are you trying to solve?

When I was using [jaeger-clickhouse](https://github.com/jaegertracing/jaeger-clickhouse), I found that WriteSpan via grpc stream will reduce the CPU utilization of jaeger and increase the throughput. So I made a pull request to jaeger, which supports grpc stream. But this still requires plugin support.

ref: https://github.com/jaegertracing/jaeger/issues/3636

### PR DESCRIPTION
**Pull request by vuuihc**
## Which problem is this PR solving?
Resolves #109

## Short description of the changes
support write span via grpc stream

### CODE REVIEW

**Comment by vuuihc** [comment]
hi @pavolloffay @nickbp @EinKrebs 
If you have time, can you help to review this mr?

**Comment by nickbp** [comment]
The changes look good in principle to me, thanks for finding this optimization!

It looks like there are some compile-time errors relating to dependencies in CI, would you be able to take a look? Should be able to exercise the tests locally with e.g. `make test`/`make e2e-tests`/`make integration-test` (see also [CI config](https://github.com/jaegertracing/jaeger-clickhouse/blob/main/.github/workflows/build.yaml) )

**Comment by vuuihc** [comment]
@nickbp I fixed all the errors in tests, please review again, thanks.

**Comment by nickbp** [comment]
Great, looks like it's passing CI as well. Thanks!

**Pull request merged**
